### ISSUE TITLE
ModuleNotFoundError: No module named 'pysqlcipher3'`

### ISSUE THREAD

**Issue by tkrunning** [mattsta/signal-backup#1]
I'm getting this issue (MacOS) when trying to run scab.py

`Traceback (most recent call last):`
`  File "scab.py", line 3, in <module>`
`    from pysqlcipher3 import dbapi2 as sqlcipher`
`ModuleNotFoundError: No module named 'pysqlcipher3'`

Any idea what's wrong?

**Comment by mattsta** [comment]
Better late than never!

You'll need to install `sqlcipher` and the python library `pysqlcipher3` with something like:

```bash
brew install sqlcipher
pip3 install pysqlcipher3 --user
```

**Comment by ekkis** [comment]
this should be documented on the main page: https://matt.sh/signal-backup  -- also, the `cd signal-backup` line needs to be *before* the pip3 install

**Comment by ekkis** [comment]
what's odd is that the `requirements.txt` does list `pysqlcipher3` so I don't know why it needs to be installed manually
